### ISSUE TITLE
QR Codes count double for statistics

### ISSUE THREAD

**Issue by ariejan** [ariejan/firefly#79]
QR codes work nicely, but opening `http://localhost:2300/2Bi.png` will count as a click. If the user then scans the QR code and opens the resulting URL `http://localhost:2300/2Bi` this counts as another click. 

The question here is: is this desired behavior or not? 

@volgorean what do you think??

**Comment by volgorean** [comment]
Ah good point.  Its probably undesirable behavior since it could potentially double the amount of registered views falsely.

I suppose the two options are either to have the QR code resolve to the final address or to not have the image count as a view.

Since not all people who view the image will follow the link and the image might be re-uploaded I should probably remove the counter from registering it as a view.

**Comment by ariejan** [comment]
I agree: the QR code should not register as a view and it should contain the short URL. There may also be the case that the QR code is re-distributed (in print or digital) and scanned by multiple users. Only the actual resolving of a short URL should register as a view.
